import { existsSync } from "node:fs";
import path from "node:path";
import {
  Document,
  Page,
  View,
  Text,
  Image,
  StyleSheet,
  Font,
} from "@react-pdf/renderer";
import type { InvoiceRow } from "@/lib/db/schema";
import {
  inr,
  toRupees,
  lineAmountPaise,
  formatDateIN,
  amountInWords,
  splitTerm,
  METHOD_LABEL,
  STATUS_LABEL,
  type InvoiceStatus,
} from "@/lib/invoices/calc";
import { UPI } from "@/lib/invoices/upi";
import { site } from "@/lib/site";

/**
 * Invoice PDF, laid out after the original invoice tool: navy header band with the
 * monogram in a white tile and the company name in gold, light cards for Bill To /
 * From / Event Schedule, a navy-headed items table, a UPI card beside the totals card
 * (green grand total, red remaining due), a Terms & Conditions card, seal and
 * signature, and the "Generated by ... | Thank you" footer. Added on top of that:
 * due date and status, payment history, amount in words, page numbers.
 *
 * Typefaces: Inter for the document (has the rupee glyph) and Space Grotesk for the
 * company name. Both ship in /public/fonts via `node scripts/fetch-fonts.mjs`; without
 * them we fall back to Helvetica and print "INR".
 */
const fontDir = path.join(process.cwd(), "public", "fonts");
const interFiles = {
  400: "Inter-400.ttf",
  500: "Inter-500.ttf",
  600: "Inter-600.ttf",
  700: "Inter-700.ttf",
} as const;
const groteskFile = "SpaceGrotesk-700.ttf";
const hasInter = Object.values(interFiles).every((f) =>
  existsSync(path.join(fontDir, f)),
);
const hasGrotesk = existsSync(path.join(fontDir, groteskFile));

if (hasInter) {
  Font.register({
    family: "Inter",
    fonts: Object.entries(interFiles).map(([w, f]) => ({
      src: path.join(fontDir, f),
      fontWeight: Number(w),
    })),
  });
}
if (hasGrotesk)
  Font.register({
    family: "Space Grotesk",
    fonts: [{ src: path.join(fontDir, groteskFile), fontWeight: 700 }],
  });
Font.registerHyphenationCallback((word) => [word]);

const FAMILY = hasInter ? "Inter" : "Helvetica";
const BRAND_FAMILY = hasGrotesk
  ? "Space Grotesk"
  : hasInter
    ? "Inter"
    : "Helvetica-Bold";
const W = (weight: 500 | 600 | 700) =>
  hasInter ? { fontWeight: weight } : { fontFamily: "Helvetica-Bold" as const };
const money = (p: number) => (hasInter ? inr(p) : inr(p, { symbol: false }));
const num = (p: number) =>
  toRupees(p).toLocaleString("en-IN", {
    minimumFractionDigits: 2,
    maximumFractionDigits: 2,
  });

/** Palette of the original tool. */
const c = {
  navy: "#09142b",
  navyMid: "#113163",
  gold: "#d4af37",
  headerText: "#d6e0f5",
  ink: "#1e293b",
  body: "#334155",
  muted: "#475569",
  faint: "#64748b",
  card: "#f8fafc",
  line: "#e2e8f0",
  frame: "#d9e2f1",
  rule: "#b0bfdd",
  green: "#0b7a4e",
  red: "#bd2d33",
  white: "#ffffff",
};

const M = 40; // side margin of the original; content width is 515
const COL = { no: 28, item: 88, qty: 48, rate: 82, amt: 87 }; // description takes the rest (182)

const s = StyleSheet.create({
  page: {
    fontFamily: FAMILY,
    fontSize: 9.5,
    color: c.body,
    paddingBottom: 60,
    lineHeight: 1.3,
  },

  band: {
    backgroundColor: c.navy,
    height: 118,
    paddingHorizontal: M,
    paddingTop: 24,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
  },
  bandRule: { height: 6, backgroundColor: c.gold },
  logoTile: {
    width: 58,
    height: 58,
    borderRadius: 8,
    backgroundColor: c.white,
    alignItems: "center",
    justifyContent: "center",
    marginRight: 12,
  },
  logo: { width: 48, height: 48 },
  kicker: { ...W(700), fontSize: 11, color: c.white, letterSpacing: 1 },
  brand: {
    fontFamily: BRAND_FAMILY,
    fontWeight: 700,
    fontSize: 22,
    color: c.gold,
    marginTop: 4,
    lineHeight: 1.1,
    letterSpacing: 0.3,
  },
  bandLine: { fontSize: 9.5, color: c.headerText, marginTop: 3 },
  detailsCard: {
    backgroundColor: c.white,
    borderRadius: 8,
    paddingVertical: 10,
    paddingHorizontal: 12,
    width: 196,
  },
  detailsTitle: { ...W(700), fontSize: 10, color: c.ink, marginBottom: 4 },
  detailsRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: 2.5,
  },
  detailsKey: { color: c.muted, fontSize: 9 },
  detailsVal: { ...W(600), color: c.ink, fontSize: 9 },

  body: { paddingHorizontal: M },
  cards: { flexDirection: "row", gap: 10, marginTop: 14 },
  card: {
    flex: 1,
    backgroundColor: c.card,
    borderRadius: 6,
    paddingVertical: 9,
    paddingHorizontal: 12,
  },
  cardTitle: { ...W(700), fontSize: 10, color: c.ink },
  cardName: { ...W(600), fontSize: 10.5, color: c.ink, marginTop: 5 },
  cardLine: { marginTop: 2, color: c.body },
  strip: {
    backgroundColor: c.card,
    borderRadius: 6,
    paddingVertical: 7,
    paddingHorizontal: 12,
    marginTop: 6,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },

  table: { marginTop: 14 },
  thead: { flexDirection: "row", backgroundColor: c.navyMid },
  th: {
    ...W(700),
    color: c.white,
    fontSize: 9.5,
    paddingVertical: 7,
    paddingHorizontal: 8,
  },
  tr: {
    flexDirection: "row",
    borderBottomWidth: 0.5,
    borderBottomColor: c.line,
    borderLeftWidth: 0.5,
    borderLeftColor: c.line,
  },
  td: {
    paddingVertical: 5.5,
    paddingHorizontal: 8,
    borderRightWidth: 0.5,
    borderRightColor: c.line,
    color: c.ink,
    justifyContent: "center",
  },
  right: { textAlign: "right" },
  center: { textAlign: "center" },

  summary: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: 14,
  },
  sumCard: {
    width: 248,
    backgroundColor: c.card,
    borderRadius: 8,
    padding: 11,
  },
  sumTitle: { ...W(700), fontSize: 11, color: c.navyMid },
  sumLine: { fontSize: 9, color: c.muted, marginTop: 2.5 },
  qrFrame: {
    width: 92,
    height: 92,
    borderWidth: 1,
    borderColor: c.frame,
    borderRadius: 8,
    alignItems: "center",
    justifyContent: "center",
  },
  qr: { width: 82, height: 82 },
  totRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: 4,
    fontSize: 10,
    color: c.body,
  },
  totRule: {
    borderTopWidth: 1,
    borderTopColor: c.rule,
    marginTop: 7,
    paddingTop: 7,
  },

  termsCard: {
    backgroundColor: c.card,
    borderRadius: 8,
    padding: 12,
    marginTop: 14,
  },
  termsTitle: { ...W(700), fontSize: 11, color: c.ink, marginBottom: 6 },
  term: {
    flexDirection: "row",
    gap: 5,
    marginTop: 2.5,
    fontSize: 9,
    color: c.body,
  },

  signRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-end",
    marginTop: 14,
  },
  seal: { width: 60, height: 60, opacity: 0.9 },
  signBlock: { width: 200, alignItems: "flex-end" },
  signLine: {
    width: 200,
    borderTopWidth: 1,
    borderTopColor: c.ink,
    marginTop: 6,
    paddingTop: 5,
    alignItems: "flex-end",
  },

  // Anchored from the top: react-pdf drops bottom-anchored fixed nodes inside the page padding.
  footer: {
    position: "absolute",
    left: M,
    right: M,
    top: 806,
    borderTopWidth: 1,
    borderTopColor: c.line,
    paddingTop: 8,
    flexDirection: "row",
    justifyContent: "space-between",
  },
  footText: { fontSize: 8, color: c.faint },
});

const statusColor: Record<InvoiceStatus, string> = {
  draft: c.muted,
  sent: c.navyMid,
  partially_paid: c.navyMid,
  paid: c.green,
  cancelled: c.red,
};

export interface InvoicePdfProps {
  invoice: InvoiceRow;
  logoSrc?: string | Buffer;
  qrSrc?: string;
  shareUrl: string;
}

export function InvoicePdf({
  invoice: inv,
  logoSrc,
  qrSrc,
  shareUrl,
}: InvoicePdfProps) {
  const status = inv.status as InvoiceStatus;
  const cancelled = status === "cancelled";
  const pending = inv.balanceDuePaise > 0 && !cancelled;
  const settled =
    !cancelled && inv.grandTotalPaise > 0 && inv.balanceDuePaise === 0;
  const eventDate =
    inv.eventStart && inv.eventEnd && inv.eventStart !== inv.eventEnd
      ? `${formatDateIN(inv.eventStart)} to ${formatDateIN(inv.eventEnd)}`
      : formatDateIN(inv.eventStart || inv.eventEnd);
  const shareHost = shareUrl.replace(/^https?:\/\//, "");

  return (
    <Document
      title={`${inv.invoiceNumber} ${site.name}`}
      author={site.name}
      subject={`Invoice ${inv.invoiceNumber} for ${inv.clientName}`}
      creator={site.name}
    >
      <Page size="A4" style={s.page}>
        <View style={s.footer} fixed>
          <Text
            style={s.footText}
          >{`Generated by ${shareHost.split("/")[0]}  |  ${site.email}`}</Text>
          <Text
            style={s.footText}
            render={({ pageNumber, totalPages }) =>
              `Thank you for choosing ${site.name}  |  Page ${pageNumber} of ${totalPages}`
            }
          />
        </View>

        {/* Header band */}
        <View style={s.band}>
          <View style={{ flexDirection: "row", alignItems: "flex-start" }}>
            {logoSrc ? (
              <View style={s.logoTile}>
                {/* eslint-disable-next-line jsx-a11y/alt-text -- react-pdf Image has no alt prop */}
                <Image src={logoSrc} style={s.logo} />
              </View>
            ) : null}
            <View>
              <Text style={s.kicker}>TAX INVOICE</Text>
              <Text style={s.brand}>{site.name.toUpperCase()}</Text>
              <Text
                style={s.bandLine}
              >{`${site.address.street}, ${site.address.locality}, ${site.address.region} ${site.address.postalCode}`}</Text>
              <Text
                style={s.bandLine}
              >{`${site.phoneDisplay}   |   ${site.email}`}</Text>
            </View>
          </View>
          <View style={s.detailsCard}>
            <Text style={s.detailsTitle}>Invoice Details</Text>
            <View style={s.detailsRow}>
              <Text style={s.detailsKey}>Invoice No</Text>
              <Text style={s.detailsVal}>{inv.invoiceNumber}</Text>
            </View>
            <View style={s.detailsRow}>
              <Text style={s.detailsKey}>Date</Text>
              <Text style={s.detailsVal}>{formatDateIN(inv.issueDate)}</Text>
            </View>
            <View style={s.detailsRow}>
              <Text style={s.detailsKey}>Due</Text>
              <Text style={s.detailsVal}>
                {inv.dueDate ? formatDateIN(inv.dueDate) : "On receipt"}
              </Text>
            </View>
            <View style={s.detailsRow}>
              <Text style={s.detailsKey}>Status</Text>
              <Text style={[s.detailsVal, { color: statusColor[status] }]}>
                {STATUS_LABEL[status]}
              </Text>
            </View>
          </View>
        </View>
        <View style={s.bandRule} />

        <View style={s.body}>
          {/* Bill To / From */}
          <View style={s.cards}>
            <View style={s.card}>
              <Text style={s.cardTitle}>Bill To</Text>
              <Text style={s.cardName}>{inv.clientName}</Text>
              {inv.clientAddress ? (
                <Text style={s.cardLine}>{inv.clientAddress}</Text>
              ) : null}
              {inv.clientPhone ? (
                <Text style={s.cardLine}>{inv.clientPhone}</Text>
              ) : null}
              {inv.clientEmail ? (
                <Text style={s.cardLine}>{inv.clientEmail}</Text>
              ) : null}
            </View>
            <View style={s.card}>
              <Text style={s.cardTitle}>From</Text>
              <Text style={s.cardName}>{site.name}</Text>
              <Text
                style={s.cardLine}
              >{`${site.address.street}, ${site.address.locality}, ${site.address.region} ${site.address.postalCode}`}</Text>
              <Text style={s.cardLine}>{site.phoneDisplay}</Text>
              <Text style={s.cardLine}>{site.email}</Text>
            </View>
          </View>

          {/* Event schedule */}
          <View style={s.strip}>
            <View>
              <Text style={s.cardTitle}>Event Schedule</Text>
              <Text style={s.cardLine}>
                {inv.eventTitle || "Live event production"}
              </Text>
            </View>
            <View style={{ alignItems: "flex-end" }}>
              <Text style={[W(600), { color: c.ink }]}>
                {eventDate || "Date as agreed"}
              </Text>
              {inv.venue ? <Text style={s.cardLine}>{inv.venue}</Text> : null}
            </View>
          </View>

          {/* Items */}
          <View style={s.table}>
            <View style={s.thead} fixed>
              <Text style={[s.th, s.center, { width: COL.no }]}>#</Text>
              <Text style={[s.th, { width: COL.item }]}>Item</Text>
              <Text style={[s.th, { flex: 1 }]}>Description</Text>
              <Text style={[s.th, s.right, { width: COL.qty }]}>Qty</Text>
              <Text style={[s.th, s.right, { width: COL.rate }]}>
                Rate (INR)
              </Text>
              <Text style={[s.th, s.right, { width: COL.amt }]}>
                Amount (INR)
              </Text>
            </View>
            {inv.items.map((l, i) => (
              <View
                key={i}
                style={[s.tr, i % 2 === 1 ? { backgroundColor: c.card } : {}]}
                wrap={false}
              >
                <View style={[s.td, { width: COL.no }]}>
                  <Text style={s.center}>{String(i + 1)}</Text>
                </View>
                <View style={[s.td, { width: COL.item }]}>
                  <Text style={W(500)}>{l.title || "-"}</Text>
                </View>
                <View style={[s.td, { flex: 1 }]}>
                  <Text style={{ color: c.body }}>{l.description || "-"}</Text>
                </View>
                <View style={[s.td, { width: COL.qty }]}>
                  <Text style={s.right}>{String(l.quantity)}</Text>
                </View>
                <View style={[s.td, { width: COL.rate }]}>
                  <Text style={s.right}>{num(l.ratePaise)}</Text>
                </View>
                <View style={[s.td, { width: COL.amt }]}>
                  <Text style={[s.right, W(500)]}>
                    {num(lineAmountPaise(l))}
                  </Text>
                </View>
              </View>
            ))}
          </View>

          {/* UPI card + totals card */}
          <View style={s.summary} wrap={false}>
            <View style={s.sumCard}>
              <Text style={s.sumTitle}>UPI Payment</Text>
              <Text style={s.sumLine}>{`UPI ID: ${UPI.id}`}</Text>
              <Text style={s.sumLine}>{`Reference: ${inv.invoiceNumber}`}</Text>
              {pending && qrSrc ? (
                <View
                  style={{
                    flexDirection: "row",
                    gap: 10,
                    marginTop: 8,
                    alignItems: "center",
                  }}
                >
                  <View style={s.qrFrame}>
                    {/* eslint-disable-next-line jsx-a11y/alt-text -- react-pdf Image has no alt prop */}
                    <Image src={qrSrc} style={s.qr} />
                  </View>
                  <View style={{ flex: 1 }}>
                    <Text
                      style={[s.sumLine, W(600), { color: c.ink }]}
                    >{`Pay: ${money(inv.balanceDuePaise)}`}</Text>
                    <Text style={s.sumLine}>Scan QR to pay</Text>
                    <Text style={s.sumLine}>Share screenshot</Text>
                    <Text style={s.sumLine}>after transfer.</Text>
                  </View>
                </View>
              ) : cancelled ? (
                <Text style={[s.sumLine, { color: c.red, marginTop: 14 }]}>
                  Invoice cancelled. No payment due.
                </Text>
              ) : (
                <View style={{ marginTop: 14 }}>
                  <Text style={[s.sumLine, { color: c.green }]}>
                    No pending amount.
                  </Text>
                  <Text style={[s.sumLine, { color: c.green }]}>
                    Payment completed.
                  </Text>
                </View>
              )}
              {inv.payments.length ? (
                <View
                  style={{
                    marginTop: 10,
                    borderTopWidth: 1,
                    borderTopColor: c.frame,
                    paddingTop: 6,
                  }}
                >
                  <Text style={[W(600), { fontSize: 8.5, color: c.ink }]}>
                    Payments received
                  </Text>
                  {inv.payments.map((p) => (
                    <View
                      key={p.id}
                      style={{
                        flexDirection: "row",
                        justifyContent: "space-between",
                        gap: 8,
                        marginTop: 2,
                      }}
                    >
                      <Text
                        style={{ fontSize: 8.5, color: c.muted, flex: 1 }}
                      >{`${formatDateIN(p.date)}  ${METHOD_LABEL[p.method]}${p.reference ? `, ${p.reference}` : ""}`}</Text>
                      <Text
                        style={[
                          W(500),
                          {
                            fontSize: 8.5,
                            color: c.green,
                            width: 72,
                            textAlign: "right",
                          },
                        ]}
                      >
                        {money(p.amountPaise)}
                      </Text>
                    </View>
                  ))}
                </View>
              ) : null}
            </View>

            <View style={s.sumCard}>
              <View style={[s.totRow, { marginTop: 0 }]}>
                <Text>Subtotal:</Text>
                <Text>{money(inv.subtotalPaise)}</Text>
              </View>
              {inv.discountPaise > 0 ? (
                <View style={s.totRow}>
                  <Text>Discount:</Text>
                  <Text>{`- ${money(inv.discountPaise)}`}</Text>
                </View>
              ) : null}
              {inv.gstRateBp > 0 ? (
                <View style={s.totRow}>
                  <Text>{`GST @ ${inv.gstRateBp / 100}%:`}</Text>
                  <Text>{money(inv.gstPaise)}</Text>
                </View>
              ) : null}
              <View style={s.totRow}>
                <Text>Advance Paid:</Text>
                <Text>{money(inv.advancePaidPaise)}</Text>
              </View>
              <View style={[s.totRow, s.totRule]}>
                <Text style={[W(700), { fontSize: 13, color: c.ink }]}>
                  Grand Total:
                </Text>
                <Text style={[W(700), { fontSize: 13, color: c.green }]}>
                  {money(inv.grandTotalPaise)}
                </Text>
              </View>
              <View style={s.totRow}>
                <Text style={[W(700), { fontSize: 12, color: c.ink }]}>
                  Remaining Due:
                </Text>
                <Text
                  style={[
                    W(700),
                    { fontSize: 12, color: pending ? c.red : c.green },
                  ]}
                >
                  {cancelled ? money(0) : money(inv.balanceDuePaise)}
                </Text>
              </View>
              <Text
                style={{ fontSize: 8.5, color: c.muted, marginTop: 8 }}
              >{`In words: ${amountInWords(inv.grandTotalPaise)}`}</Text>
            </View>
          </View>

          {/* Terms & Conditions with seal and signature, kept on one page together */}
          <View wrap={false}>
            {inv.terms.length || inv.notes ? (
              <View style={s.termsCard}>
                {inv.notes ? (
                  <View style={{ marginBottom: inv.terms.length ? 8 : 0 }}>
                    <Text style={s.termsTitle}>Notes</Text>
                    <Text style={{ fontSize: 9, color: c.body }}>
                      {inv.notes}
                    </Text>
                  </View>
                ) : null}
                {inv.terms.length ? (
                  <>
                    <Text style={s.termsTitle}>Terms & Conditions</Text>
                    {inv.terms.map((t, i) => {
                      const parts = splitTerm(t);
                      return (
                        <View key={i} style={s.term}>
                          <Text>-</Text>
                          <Text style={{ flex: 1 }}>
                            {parts ? (
                              <Text style={W(600)}>{`${parts.label}: `}</Text>
                            ) : null}
                            {parts ? parts.text : t}
                          </Text>
                        </View>
                      );
                    })}
                  </>
                ) : null}
              </View>
            ) : null}

            <View style={s.signRow}>
              <Text style={{ fontSize: 9, color: c.muted }}>
                {settled
                  ? "Received with thanks."
                  : "Thank you for your business."}
              </Text>
              <View style={s.signBlock}>
                {/* eslint-disable-next-line jsx-a11y/alt-text -- react-pdf Image has no alt prop */}
                {logoSrc ? <Image src={logoSrc} style={s.seal} /> : null}
                <View style={s.signLine}>
                  <Text
                    style={[W(700), { color: c.ink, fontSize: 9.5 }]}
                  >{`For ${site.name}`}</Text>
                  <Text style={{ color: c.muted, fontSize: 9 }}>
                    Authorised Signatory
                  </Text>
                </View>
              </View>
            </View>
          </View>
        </View>
      </Page>
    </Document>
  );
}
