"use client";

import { Suspense, useEffect, useMemo, useRef } from "react";
import * as THREE from "three";
import { useFrame, useThree } from "@react-three/fiber";
import { useTexture } from "@react-three/drei";

interface TrussBannerProps {
  /** Printed width of the banner */
  width?: number;
  height?: number;
  /** World Y of the top edge — where the straps hold it */
  top?: number;
  /** World Z of the banner. Negative hangs it upstage of the fixtures, so nothing crosses the beams. */
  z?: number;
  /** Chord the straps clip to, as [y, z] */
  hang?: [number, number];
  accent?: string;
  /** Gold-on-transparent lockup, generated by scripts/brand/export-site.mjs */
  src?: string;
}

/**
 * A plane that hangs like fabric: it bows toward the room and dips between the two straps,
 * strongest at mid-span and nothing at the hang points. `span` is the banner's full width so
 * the print laid over the fabric follows exactly the same curve.
 */
function drapedPlane(width: number, height: number, span: number, offset: number, bow: number, dip: number) {
  const geo = new THREE.PlaneGeometry(width, height, 28, 1);
  const pos = geo.attributes.position;
  for (let i = 0; i < pos.count; i++) {
    const t = Math.min(1, Math.abs((2 * pos.getX(i)) / span));
    const k = 1 - t * t;
    pos.setZ(i, pos.getZ(i) + offset + bow * k);
    pos.setY(i, pos.getY(i) - dip * k);
  }
  pos.needsUpdate = true;
  geo.computeVertexNormals();
  return geo;
}

/**
 * The printed lockup, front and back. A real double-sided banner is printed twice, so the
 * rear copy gets a mirrored texture and reads the right way round when the camera orbits behind.
 * Suspends on the texture by itself, inside the banner, so the fabric never waits for it.
 */
function BannerPrint({ src, width, height, span, bow, dip }: { src: string; width: number; height: number; span: number; bow: number; dip: number }) {
  const map = useTexture(src);
  const maxAnisotropy = useThree((s) => s.gl.capabilities.getMaxAnisotropy());

  const back = useMemo(() => {
    map.colorSpace = THREE.SRGBColorSpace;
    map.anisotropy = Math.min(8, maxAnisotropy);
    const mirrored = map.clone();
    mirrored.wrapS = THREE.RepeatWrapping;
    mirrored.repeat.x = -1;
    mirrored.offset.x = 1;
    mirrored.needsUpdate = true;
    return mirrored;
  }, [map, maxAnisotropy]);
  useEffect(() => () => back.dispose(), [back]);

  const { front: frontGeo, back: backGeo } = useMemo(() => {
    const img = map.image as { width: number; height: number };
    const aspect = img.width / img.height;
    let h = height * 0.8;
    let w = h * aspect;
    if (w > width * 0.86) {
      w = width * 0.86;
      h = w / aspect;
    }
    return { front: drapedPlane(w, h, span, 0.014, bow, dip), back: drapedPlane(w, h, span, -0.014, bow, dip) };
  }, [map, width, height, span, bow, dip]);
  useEffect(
    () => () => {
      frontGeo.dispose();
      backGeo.dispose();
    },
    [frontGeo, backGeo],
  );

  // alphaTest keeps the print depth-correct against the fabric behind it; the touch of emissive
  // means the gold still reads when no fixture happens to be pointing at the banner.
  return (
    <>
      <mesh geometry={frontGeo}>
        <meshStandardMaterial map={map} emissiveMap={map} emissive="#ffffff" emissiveIntensity={0.22} transparent alphaTest={0.02} roughness={0.55} metalness={0.15} side={THREE.FrontSide} />
      </mesh>
      <mesh geometry={backGeo}>
        <meshStandardMaterial map={back} emissiveMap={back} emissive="#ffffff" emissiveIntensity={0.22} transparent alphaTest={0.02} roughness={0.55} metalness={0.15} side={THREE.BackSide} />
      </mesh>
    </>
  );
}

/**
 * Branded banner strapped under the main truss — the MIHIR lockup on black fabric, printed
 * both sides, with a gold hairline top and bottom. It hangs upstage of the moving heads so it
 * never blocks a beam, and sways a degree or so the way a real hung banner does in room air.
 */
export function TrussBanner({
  width = 5.6,
  height = 2.1,
  top = 5.78,
  z = -0.62,
  hang = [5.99, -0.21],
  accent = "#ffb800",
  src = "/logo-banner.png",
}: TrussBannerProps) {
  const sway = useRef<THREE.Group>(null);

  const bow = width * 0.018;
  const dip = width * 0.01;
  const { fabric, rules } = useMemo(
    () => ({ fabric: drapedPlane(width, height, width, 0, bow, dip), rules: drapedPlane(width * 0.98, 0.028, width, 0.016, bow, dip) }),
    [width, height, bow, dip],
  );
  useEffect(
    () => () => {
      fabric.dispose();
      rules.dispose();
    },
    [fabric, rules],
  );

  // Straps: one at each top corner, angled back to the truss chord.
  const [hangY, hangZ] = hang;
  const dy = top - hangY;
  const dz = z - hangZ;
  const strapLength = Math.hypot(dy, dz);
  const strapTilt = Math.atan2(dz, dy);

  useFrame(({ clock }) => {
    const g = sway.current;
    if (!g) return;
    const t = clock.elapsedTime;
    g.rotation.x = Math.sin(t * 0.42) * 0.012;
    g.rotation.z = Math.sin(t * 0.31 + 1.1) * 0.005;
  });

  return (
    <group>
      {[-1, 1].map((s) => (
        <group key={s} position={[(s * width) / 2, 0, 0]}>
          <mesh position={[0, hangY, hangZ]}>
            <boxGeometry args={[0.1, 0.12, 0.12]} />
            <meshStandardMaterial color="#7d8794" metalness={0.9} roughness={0.35} />
          </mesh>
          <mesh position={[0, (hangY + top) / 2, (hangZ + z) / 2]} rotation={[strapTilt, 0, 0]}>
            <boxGeometry args={[0.05, strapLength, 0.02]} />
            <meshStandardMaterial color="#2b3240" roughness={0.85} />
          </mesh>
        </group>
      ))}

      {/* Pivot sits on the hang line, so the sway swings from the straps rather than the middle. */}
      <group position={[0, top, z]}>
        <group ref={sway}>
          <group position={[0, -height / 2, 0]}>
            <mesh geometry={fabric}>
              <meshStandardMaterial color="#0b0e14" roughness={0.94} metalness={0.04} side={THREE.DoubleSide} />
            </mesh>
            {[1, -1].map((s) => (
              <mesh key={s} geometry={rules} position={[0, (s * (height - 0.2)) / 2, 0]}>
                <meshBasicMaterial color={accent} toneMapped={false} transparent opacity={0.85} side={THREE.DoubleSide} />
              </mesh>
            ))}
            <Suspense fallback={null}>
              <BannerPrint src={src} width={width} height={height} span={width} bow={bow} dip={dip} />
            </Suspense>
          </group>
        </group>
      </group>
    </group>
  );
}
